version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: northwind_db
    environment:
      POSTGRES_DB: northwind
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./northwind.sql:/docker-entrypoint-initdb.d/northwind.sql

volumes:
  postgres_data:
